### ISSUE TITLE
Use GulpJs

### ISSUE THREAD

**Issue by Zikama** [ndiadedev/Mobile-Web-Specialist-App#2]
Since the _scope_ of the project runs under _/build_,
>now instead of npm run build, which just build up the scope for the project.\
let's build that when we just run _**npm run start**_ command.
in package.json, make main to (  **_main:  gulpfile.js_**/or any that contain your gulp codes  ).
gulpfile.js is where we make all the work done.
we pipe all the files that we need to our dest repository which is /build,
I am currently working on that, I think someone here can do that better than I,
that's why i want you to try it too
`Begin coding...`

**Comment by ndiadedev** [comment]
Thank for this pertinent notice Zikama! 
Currently, the project is not running under Gulp.js i have used npm package manager because in Workbox Librery environment, we have 3 choices: Gulp, Npm and Web pack.
Concerning **npm run start** cmd it's just used for starting the server and runing the app into the **localhost:8081** port  address into the browser.
So Like you said, possibilities are opened and you can test it in gulp so to find out the final point! 
Soon i'll make a wiki page for the project so to give more explainations through the building process
